spring.application.name=ai_agent_projet_academique


spring.ai.mistralai.api-key=eXUQ8W7keo7fg47U1XJkjQGdrjJbPdxp
spring.ai.mistralai.chat.options.model=mistral-large-latest
spring.ai.mistralai.chat.options.temperature=0.7
spring.ai.mistralai.embedding.options.model=mistral-embed


spring.ai.openai.api-key=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
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.chat.options.model=llama3-8b-8192
spring.ai.openai.chat.options.temperature=0.7




spring.datasource.url=jdbc:h2:mem:aiagentdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.web.cors.allowed-origins=http://localhost:4200